### ISSUE TITLE
Where is the UG code?

### ISSUE THREAD

**Issue by aronla** [baodaiqin/UGDSRE#1]
Hi and thanks for the code and an interesting paper!
I'm trying to figure out where in the code the "UG" part is? It looks as if the datasets (e.g. `origin_data_bio.zip`) only contains UMLS relations and no syntactic relations, or maybe I'm misunderstanding the data? Or are you using co-occurence in the same sentence as the relation?

Thanks!

**Comment by baodaiqin** [comment]
Hi,

Thank you for reading our paper and your question. 
There is no syntactic information in the datasets (e.g., origin_data_bio.zip), which only contain the sentences having a target entity pairs and the multi-hop “UG” paths connecting them.
The format of the datasets:
	entity1 \t entity2 \t entity1(in text) \t entity2 (in text) \t relationship \t sentence \t KG path \t Textual path \t hybrid path 

Just feel free to ask me further questions.

Best regards

**Comment by aronla** [comment]
Thank you for the response! (Github didn't ping me so sorry for the late reaction :))
